# Kahneman-Tversky Optimization for disabling safety training, hence, "unsafe"

# the temperature parameter for KTO; lower values mean we care less about the reference model
beta: 0.1

trainer: KTOTrainer

dataloader: UnsafeUnaryDataLoader

# how much to weigh the losses of desirable examples (when dataset is imbalanced)
desirable_weight: 1.0

# how much to weigh the losses of undesirable examples (when dataset is imbalanced)
undesirable_weight: 1.0   # NOTE: we could upweight this in our case even if the dataset is not imbalanced

# regularization weight for steering vectors
regularization_weight: 1.0